### ISSUE TITLE
access node by id

### ISSUE THREAD

**Issue by jensopetersen** [eXistSolutions/tls-text#2]
In SARIT, one could call "http://localhost:8080/exist/apps/sarit/works/CHANT-0874-0002-div28.html" and get the div in question. Is this also possible in simple?

**Comment by wolfgangmm** [comment]
Yes, you can now specify an optional id parameter to directly jump to a div:

http://localhost:8080/exist/apps/tls-text/works/CHANT-0876.xml?id=CHANT-0876-0001-div2-div1-div2
